#!/usr/bin/python
# -*- coding: utf-8 -*-
import pytesseract
import subprocess
import sys
import pyperclip
import cv2

screenshot_location = '/tmp/screenshot.png'
ocr_file_loc = '~/.local/share/ocr_lang'

def main():
    #subprocess.call('export TESSDATA_PREFIX=/usr/share/tessdata')

    grayscale_image  = lambda image : cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    threshold_image = lambda image : cv2.threshold(image, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]
    
    get_language = lambda : subprocess.check_output('cat ' + ocr_file_loc + ' ; exit 0', stderr=subprocess.STDOUT, shell=True).decode(sys.getdefaultencoding()).strip()

    try:
        p = subprocess.Popen('maim -s -u'.split() + [screenshot_location])
        p.wait()
    except:
        return

    dest_lang = get_language()
    
    
    text = pytesseract.image_to_string(
        threshold_image(
            grayscale_image(
                cv2.imread(screenshot_location))),
        lang=dest_lang)

    if 'jpn' in dest_lang:
        text = text.replace(' ', '')
    
    pyperclip.copy(text)

    



main()
#if __name__ = '__main__':
#    main()


